version: '3.6'

services:
  # Backend API
  api:
    container_name: backend-api
    build: ./
    working_dir: /usr/src/app
    environment:
      REDIS_HOST: redis
      # POSTGRES_URI: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
      # - yarn-cache:/usr/local/share/.cache/yarn/v1/
    networks: 
      - nw_database
      - nw_redis

  # Postgres Database
  postgres:
    container_name: backend-db
    build: ./sql/
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks: 
      - nw_database

  # Redis
  redis:
    container_name: backend-redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - nw_redis


volumes: 
  db-data:
  # yarn-cache:

networks: 
  nw_database:
  nw_redis: