version: '3.6'

services:
  # Backend API
  api:
    container_name: backend-api
    build: ./
    entrypoint: yarn debug
    working_dir: /usr/src/app
    environment:
      WEB_PORT: 3005
      REDIS_HOST: redis
      # POSTGRES_URI: postgres://postgres:${DB_PASSWORD}@postgres:5432/
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3005:3005"
      # NODE DEBUG PORTS:
      - "9222:9222"
    volumes:
      - ./:/usr/src/app
      # - yarn-cache:/usr/local/share/.cache/yarn/v1/
    networks: 
      - nw_database
      - nw_redis

  # Postgres Database
  postgres:
    container_name: backend-db
    build: ./sql/
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks: 
      - nw_database

  # Redis
  redis:
    container_name: backend-redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - nw_redis

volumes: 
  db-data:
  # yarn-cache:

networks: 
  nw_database:
  nw_redis: